# Generated by Django 2.2.2 on 2021-10-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0004_auto_20211002_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='draw_date',
            field=models.DateField(null=True),
        ),
    ]
